#!/usr/bin/env bash
# gen-codemap.sh — regenerate the auto sections of CODEBASE.md.
#
# Preserves anything below the "HAND-WRITTEN BELOW" marker.

set -euo pipefail
shopt -s globstar nullglob

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

CODEMAP=".agent/CODEBASE.md"
MARKER="<!-- HAND-WRITTEN BELOW — EDIT FREELY -->"

if [[ ! -f "$CODEMAP" ]]; then
    echo "ERROR: $CODEMAP not found. Run agent-init first." >&2
    exit 1
fi

# Extract the hand-written portion (everything from the marker onward)
HAND_WRITTEN=$(awk -v marker="$MARKER" '
    found { print }
    $0 ~ marker { found=1; print }
' "$CODEMAP")

if [[ -z "$HAND_WRITTEN" ]]; then
    echo "WARN: marker not found in $CODEMAP; appending fresh hand-written stub" >&2
    HAND_WRITTEN="$MARKER

## Architecture

(write this)
"
fi

# Pick a directory tree tool
if command -v tree >/dev/null 2>&1; then
    TREE_CMD="tree -L 3 --charset utf-8 -I 'node_modules|target|dist|.git|.next|__pycache__|.venv|venv|build|.agent|clients' --noreport ."
elif command -v fd >/dev/null 2>&1; then
    TREE_CMD="fd --max-depth 3 --hidden --exclude .git --exclude node_modules --exclude target --exclude dist --exclude .agent --exclude clients"
else
    TREE_CMD="find . -maxdepth 3 -type d -not -path '*/\.*' -not -path '*/node_modules*' -not -path '*/target*' -not -path '*/dist*' -not -path '*/clients*'"
fi

# Detect a few common API-surface signals; this is intentionally rough
api_surface() {
    local found=0
    if compgen -G "**/*.rs" > /dev/null 2>&1; then
        echo "### Rust"
        rg --no-heading -n '^pub (fn|struct|enum|trait|mod) ' --type rust 2>/dev/null \
            | head -100 || true
        found=1
    fi
    if compgen -G "**/*.go" > /dev/null 2>&1; then
        echo "### Go"
        rg --no-heading -n '^func [A-Z]|^type [A-Z]' --type go 2>/dev/null \
            | head -100 || true
        found=1
    fi
    if compgen -G "**/*.ts" > /dev/null 2>&1 || compgen -G "**/*.tsx" > /dev/null 2>&1; then
        echo "### TypeScript"
        rg --no-heading -n '^export (function|class|interface|type|const|enum) ' --type ts 2>/dev/null \
            | head -100 || true
        found=1
    fi
    if compgen -G "**/*.py" > /dev/null 2>&1; then
        echo "### Python"
        rg --no-heading -n '^(class |def )[A-Za-z_]' --type py 2>/dev/null \
            | grep -v '^.*:def _' \
            | head -100 || true
        found=1
    fi
    if [[ $found -eq 0 ]]; then
        echo "_No source files detected yet._"
    fi
}

# Build the new file
{
    cat <<'HEADER'
# Codebase Map

> This file has two parts: an auto-generated section (regenerated by `.agent/scripts/gen-codemap.sh`) and a hand-written section that explains the architecture. **Don't edit above the marker** — your changes will be lost.

<!-- AUTO-GENERATED BELOW — DO NOT EDIT -->

_Generated by `gen-codemap.sh`. Re-run after structural changes._

## Directory tree

```
HEADER

    eval "$TREE_CMD" 2>/dev/null || echo "(tree generation failed)"

    cat <<'MID'
```

## Public API surface

MID

    api_surface

    echo
    echo "## Stats"
    echo
    if command -v tokei >/dev/null 2>&1; then
        echo '```'
        tokei --output yaml 2>/dev/null | head -50 || tokei 2>/dev/null | head -30 || true
        echo '```'
    else
        echo '```'
        echo "Total tracked files: $(git ls-files 2>/dev/null | wc -l)"
        echo '```'
    fi
    echo

    echo "$HAND_WRITTEN"
} > "$CODEMAP.tmp"

mv "$CODEMAP.tmp" "$CODEMAP"
echo "✓ regenerated $CODEMAP"
