#!/usr/bin/env bash
# gen-codemap.sh — regenerate the auto sections of CODEBASE.md for an IaC repo.
#
# Overrides the common gen-codemap.sh. Surfaces:
#   - directory tree
#   - Terraform modules under modules/ or terraform/modules/
#   - Terraform variable / output / resource declarations
#   - Ansible roles under roles/ or ansible/roles/
#   - Ansible playbook task counts under playbooks/ or ansible/playbooks/
#
# Preserves anything below the "HAND-WRITTEN BELOW" marker.

set -euo pipefail
shopt -s globstar nullglob

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

CODEMAP=".agent/CODEBASE.md"
MARKER="<!-- HAND-WRITTEN BELOW — EDIT FREELY -->"

if [[ ! -f "$CODEMAP" ]]; then
    echo "ERROR: $CODEMAP not found. Run agent-init first." >&2
    exit 1
fi

# Extract the hand-written portion (everything from the marker onward)
HAND_WRITTEN=$(awk -v marker="$MARKER" '
    found { print }
    $0 ~ marker { found=1; print }
' "$CODEMAP")

if [[ -z "$HAND_WRITTEN" ]]; then
    echo "WARN: marker not found in $CODEMAP; appending fresh hand-written stub" >&2
    HAND_WRITTEN="$MARKER

## Architecture

(write this)
"
fi

# Pick a directory tree tool
if command -v tree >/dev/null 2>&1; then
    TREE_CMD="tree -L 3 --charset utf-8 -I '.git|.terraform|.venv|venv|__pycache__|node_modules|.agent' --noreport ."
elif command -v fd >/dev/null 2>&1; then
    TREE_CMD="fd --max-depth 3 --hidden --exclude .git --exclude .terraform --exclude .venv --exclude __pycache__ --exclude .agent"
else
    TREE_CMD="find . -maxdepth 3 -type d -not -path '*/\.git*' -not -path '*/\.terraform*' -not -path '*/\.venv*'"
fi

# Find Terraform modules. Two common layouts: top-level modules/ or terraform/modules/.
list_terraform_modules() {
    local roots=(modules terraform/modules)
    local found=0
    for root in "${roots[@]}"; do
        if [[ -d "$root" ]]; then
            for mod in "$root"/*/; do
                [[ -d "$mod" ]] || continue
                # Count .tf files in the module for a rough size signal.
                local tf_count
                tf_count=$(find "$mod" -maxdepth 1 -name '*.tf' -type f 2>/dev/null | wc -l | tr -d ' ')
                echo "- \`$mod\` — $tf_count .tf file(s)"
                found=1
            done
        fi
    done
    if [[ $found -eq 0 ]]; then
        echo "_No Terraform modules found._"
    fi
}

# Surface Terraform declarations (variable / output / resource / module blocks).
terraform_decls() {
    if ! compgen -G "**/*.tf" > /dev/null 2>&1; then
        echo "_No Terraform files found._"
        return
    fi
    grep -rEn --include='*.tf' \
        --exclude-dir=.git --exclude-dir=.terraform --exclude-dir=.venv \
        '^(variable|output|resource|module|data) ' . 2>/dev/null \
        | sed 's|^\./||' \
        | sort -t: -k1,1 -k2,2n \
        | head -200 || echo "_(no declarations found)_"
}

# Find Ansible roles.
list_ansible_roles() {
    local roots=(roles ansible/roles)
    local found=0
    for root in "${roots[@]}"; do
        if [[ -d "$root" ]]; then
            for role in "$root"/*/; do
                [[ -d "$role" ]] || continue
                # Skip .gitkeep-only directories.
                if [[ -z "$(find "$role" -mindepth 1 -not -name '.gitkeep' -print -quit 2>/dev/null)" ]]; then
                    continue
                fi
                local task_file="$role/tasks/main.yml"
                local task_count=0
                if [[ -f "$task_file" ]]; then
                    task_count=$(grep -cE '^\s*- (name|ansible\.builtin)' "$task_file" 2>/dev/null || echo 0)
                fi
                echo "- \`$role\` — ~$task_count task(s) in tasks/main.yml"
                found=1
            done
        fi
    done
    if [[ $found -eq 0 ]]; then
        echo "_No Ansible roles found._"
    fi
}

# Find Ansible playbooks.
list_ansible_playbooks() {
    local roots=(playbooks ansible/playbooks)
    local found=0
    for root in "${roots[@]}"; do
        if [[ -d "$root" ]]; then
            for pb in "$root"/*.yml "$root"/*.yaml; do
                [[ -f "$pb" ]] || continue
                local task_count
                task_count=$(grep -cE '^\s*- (name|ansible\.builtin)' "$pb" 2>/dev/null || echo 0)
                echo "- \`$pb\` — ~$task_count task(s)"
                found=1
            done
        fi
    done
    if [[ $found -eq 0 ]]; then
        echo "_No Ansible playbooks found._"
    fi
}

# Build the new file
{
    cat <<'HEADER'
# Codebase Map

> This file has two parts: an auto-generated section (regenerated by `.agent/scripts/gen-codemap.sh`) and a hand-written section that explains the architecture. **Don't edit above the marker** — your changes will be lost.

<!-- AUTO-GENERATED BELOW — DO NOT EDIT -->

_Generated by `gen-codemap.sh` (iac flavor). Re-run after structural changes._

## Directory tree

```
HEADER

    eval "$TREE_CMD" 2>/dev/null || echo "(tree generation failed)"

    cat <<'MID1'
```

## Terraform inventory

### Modules

MID1

    list_terraform_modules

    cat <<'MID2'

### Declarations

```
MID2

    terraform_decls

    cat <<'MID3'
```

## Ansible inventory

### Roles

MID3

    list_ansible_roles

    cat <<'MID4'

### Playbooks

MID4

    list_ansible_playbooks

    echo
    echo "## Stats"
    echo
    echo '```'
    echo "Total tracked files: $(git ls-files 2>/dev/null | wc -l)"
    echo "Terraform .tf files: $(find . -name '*.tf' -not -path './.terraform/*' -not -path './.git/*' 2>/dev/null | wc -l)"
    echo "Ansible .yml files:  $(find . \( -path '*/playbooks/*.yml' -o -path '*/roles/*/*.yml' -o -path '*/group_vars/*.yml' -o -path '*/host_vars/*.yml' \) -not -path './.git/*' 2>/dev/null | wc -l)"
    echo '```'
    echo

    echo "$HAND_WRITTEN"
} > "$CODEMAP.tmp"

mv "$CODEMAP.tmp" "$CODEMAP"
echo "✓ regenerated $CODEMAP (iac flavor)"
